/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCompany: typeof import('./src/components/UserCompany.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UsersTable: typeof import('./src/components/UsersTable.vue')['default']
  }
}
